### PR TITLE
Fix issue 769

### LINKED ISSUE #769: remove old serialization `read/write_restart_vectors()`
after the following PRs are merged:
~#729~ ~#731~ ~#732~ ~#734~
IT"S TIME!

### PR DESCRIPTION
**Pull request by richardschu**
fixes #769 
i.e., removes the old serialization and adapts the tests to reading/writing a scalar to a `boost::archive::text_iarchive` to check if that part is working as it is still needed for de-/serialization.

### CODE REVIEW

File: include/exadg/time_integration/time_int_explicit_runge_kutta_base.cpp [hunk 1]
```diff
@@ -162,28 +157,17 @@ TimeIntExplRKBase<Number>::do_read_restart(std::ifstream & in)
 
   // Note that the operations done here must be in sync with the output.
 
-  // 1. ranks
```
Comment (richardschu) [inline include/exadg/time_integration/time_int_explicit_runge_kutta_base.cpp:165]: note that we do not have th constraint
`n_ranks_old == n_ranks`
anymore because we use deal.II's serialization now!

**Comment by richardschu** [comment]
merge bcs minor follow-up to #776
