### PR TITLE
fix bug in GridUtilities

### LINKED ISSUE #539: bug for simplex with TriangulationType::Serial and GridData::create_coarse_triangulations = false
The problem occurs for TriangulationType::Serial and is a problem similar as in PR #534 for the fully-distributed case.

### PR DESCRIPTION
**Pull request by nfehn**
closes #539

### CODE REVIEW

File: include/exadg/grid/grid_utilities.h [hunk 1]
```diff
@@ -429,25 +427,43 @@ create_fine_and_coarse_triangulations(
...
+    GridUtilities::create_triangulation(grid.triangulation,
+                                        grid.periodic_face_pairs,
+                                        mpi_comm,
+                                        data,
+                                        not data.create_coarse_triangulations,
+                                        lambda_create_triangulation,
+                                        data.n_refine_global,
+                                        vector_local_refinements);
+
+    // Depending on the type of multigrid implementation, the coarse triangulations need to created
```
Comment (nfehn) [inline include/exadg/grid/grid_utilities.h:449]: typo "need to be created"

**Review by peterrum — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]
