### PR TITLE
Make HDF5 an optional dependency and KineticEnergySpectrumCalculator an optional postprocessing routine

### LINKED ISSUE #419: Tests are failing if HDF5 (optional dependency) is not installed
HDF5 is declared an optional dependency. However, the tests are failing without hdf5 (at least in my case) with the message "deal.II is not compiled with HDF5!". I consider this a contradiction that needs to be resolved  (since testing is essential/mandatory, rendering hdf5 a required dependency).

I suggest to exclude hdf5-related content from testing.

### PR DESCRIPTION
**Pull request by richardschu**
closes #419

in `incompressible_navier_stokes/postprocessor/postprocessor.cpp` in the `PostProcessor::setup()`, we call among others `pointwise_output_generator.setup()` and `kinetic_energy_spectrum_calculator.setup()`.
The former requires hdf5, which is only an optional dependency as far as I know and the latter requires `elementType::Hypercube`. I moved the asserts behind a `time_control.is_active`, since the setup is called in any case, but the postprocessors might not even be active.
After the setup, the `evaluate`on the postprocessors is behind a `pointwise_output_generator.time_control.needs_evaluation()` for example. So not setting them up should be fine.

### CODE REVIEW

**Review by jh66637 — APPROVED** [review]

File: include/exadg/postprocessor/pointwise_output_generator_base.cpp [hunk 1]
```diff
@@ -145,8 +145,10 @@ PointwiseOutputGeneratorBase<dim, Number>::setup_base(
 #else
   (void)triangulation_in;
   (void)mapping_in;
-  (void)pointwise_output_data_in;
-  AssertThrow(false, dealii::ExcMessage("deal.II is not compiled with HDF5!"));
+  if(pointwise_output_data_in.time_control_data.is_active)
```
Comment (nfehn) [inline include/exadg/postprocessor/pointwise_output_generator_base.cpp:148]: Is the code in lines 102-114 actually placed correctly? Why not inside the if-statement (line 116)?

I think the `#ifdef` should also appear inside the if-statement above since this would make the coder easier to understand for the `#else` branch.

File: include/exadg/postprocessor/kinetic_energy_spectrum.cpp [hunk 2]
```diff
@@ -596,17 +596,17 @@ KineticEnergySpectrumCalculator<dim, Number>::setup(
...
-  AssertThrow(
-    dof_handler->get_triangulation().all_reference_cells_are_hyper_cube(),
-    dealii::ExcMessage(
-      "This postprocessing utility is only available for meshes consisting of hypercube elements."));
-
   clear_files = data.clear_file;
 
   time_control.setup(data_in.time_control_data);
 
   if(data_in.time_control_data.is_active)
```
Comment (nfehn) [inline include/exadg/postprocessor/kinetic_energy_spectrum.cpp:603]: This if-statement uses `data_in`, so I wonder whether we should actually shift everything before this if-statement inside the if-statement.

Comment (nfehn) [reply include/exadg/postprocessor/kinetic_energy_spectrum.cpp:603]: Then, the assert on the dof_handler/triangulation would again appear next to the assignment of the dof-handler.

Comment (richardschu) [reply include/exadg/postprocessor/kinetic_energy_spectrum.cpp:603]: Yep!

File: include/exadg/postprocessor/pointwise_output_generator_base.cpp (hunk 1 above)
Comment (richardschu) [reply include/exadg/postprocessor/pointwise_output_generator_base.cpp:148]: Yep; I think you are right. I think we should move 102-114 and the `#ifdef' inside the if.

File: include/exadg/postprocessor/kinetic_energy_spectrum.cpp [hunk 3]
```diff
@@ -593,20 +593,18 @@ KineticEnergySpectrumCalculator<dim, Number>::setup(
...
-
-  clear_files = data.clear_file;
-
-  time_control.setup(data_in.time_control_data);
-
   if(data_in.time_control_data.is_active)
   {
+    data        = data_in;
+    clear_files = data.clear_file;
+    time_control.setup(data_in.time_control_data);
```
Comment (nfehn) [inline include/exadg/postprocessor/kinetic_energy_spectrum.cpp:600]: one line above, `data` is used, so I would also use `data` here instead of `data_in`.

**Comment by nfehn** [comment]
Looks good from my side, apart from the minor aspect whether the variable with `_in` or without is used.

**Comment by nfehn** [comment]
@richardschu @jh66637 could you please have a look at issue #419 and make sure that this problem is resolved as well? Adding a reference to this issue in the description of the present PR will then automatically close that issue.

**Comment by jh66637** [comment]
I can have a look

File: include/exadg/postprocessor/pointwise_output_generator_base.cpp [hunk 4]
```diff
@@ -141,13 +140,13 @@ PointwiseOutputGeneratorBase<dim, Number>::setup_base(
       auto group = hdf5_file->create_group("PhysicalInformation");
       add_time_dataset(group, "Time");
     }
-  }
+
 #else
-  (void)triangulation_in;
-  (void)mapping_in;
-  (void)pointwise_output_data_in;
-  AssertThrow(false, dealii::ExcMessage("deal.II is not compiled with HDF5!"));
```
Comment (nfehn) [inline include/exadg/postprocessor/pointwise_output_generator_base.cpp:149]: @jh66637 isn't the main point of the present PR that this assert is currently always triggered independently of whether we want to use this postprocessing routine or not?

I understood the present PR in the way that this line currently enforces HDF5 to be a mandatory TPL for ExaDG. And this way I see a link to issue #419.

**Comment by nfehn** [comment]
@richardschu Have you encountered these problems because you have not installed HDF5 on the machine you are currently working? (I think this would help regarding the discussions in issue #419.)

File: include/exadg/postprocessor/pointwise_output_generator_base.cpp (hunk 4 above)
Comment (jh66637) [reply include/exadg/postprocessor/pointwise_output_generator_base.cpp:149]: I agree, but I can not reproduce it on my laptop.

Comment (nfehn) [reply include/exadg/postprocessor/pointwise_output_generator_base.cpp:149]: It looks like you need to find out in more detail what your local setup is doing exactly.

**Comment by richardschu** [comment]
> @richardschu Have you encountered these problems because you have not installed HDF5 on the machine you are currently working? (I think this would help regarding the discussions in issue #419.)

That was precicely the problem. I now compiled deal.II with hdf5, but I thought I might have a look at why it requires me to have it...
I am currently trying to reproduce the Assertion same way Johannes did and report back as soon as I can say more.
If this does not help, I will uninstall hdf5 again and see where the problem was. The changes proposed in this PR were what I thought the problem was, but I fixed the problem at my end in 2 ways at the same time so I cannot guarantee, that the changes proposed here (while they do make sense) do the trick.

I will upadte you guys asap.

**Comment by nfehn** [comment]
@richardschu I think there is no more inspection required from your side. I think we are now all convinced that the present PR fixes the issue.

**Comment by richardschu** [comment]
> @richardschu @jh66637 could you please have a look at issue #419 and make sure that this problem is resolved as well? Adding a reference to this issue in the description of the present PR will then automatically close that issue.

and how did that work now? It appeared on the side after you mentioned it, but do we have to specify, that this closes #419?

**Comment by nfehn** [comment]
I changed the description of the PR manually. Writing `closes #NUMBER` will then automatically close the issue once the PR is merged.

**Comment by richardschu** [comment]
> I changed the description of the PR manually. Writing `closes #NUMBER` will then automatically close the issue once the PR is merged.

oh, thanks :) !

**Review by nfehn — APPROVED** [review]
