### PR TITLE
after introduced & once again

### LINKED ISSUE #548: Structure::NonlinearOperator reinit_cell_derived fails to access ghost entries
Running the structure/bar application with multiple cores leads to assertion thrown in `NonlinearOperator::reinit_cell_derived()` (see stacktrace below). This happens only when using the NonlinearOperator together with `Preconditioner::Multigrid` (this is exactly the out-of-the-box setup).

I will try to fix this, should not be too hard to find as the `navier_stokes/poisuille` is indeed running with `mpirun -n 2`.

Here is the error + stacktrace:

`
An error occurred in line <1631> of file </homes/wiss/schussri/dealii-candi/dealii/include/deal.II/lac/la_parallel_vector.h> in function
    Number dealii::LinearAlgebra::distributed::Vector<Number, MemorySpace>::local_element(dealii::LinearAlgebra::distributed::Vector<Number, MemorySpace>::size_type) const [with Number = float; MemorySpace = dealii::MemorySpace::Host; dealii::LinearAlgebra::distributed::Vector<Number, MemorySpace>::size_type = unsigned int]
The violated condition was: 
    local_index < locally_owned_size() || vector_is_ghosted == true
Additional information: 
    You tried to read a ghost element of this vector, but it has not
    imported its ghost values.

Stacktrace:
-----------
#0  solver: dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>::local_element(unsigned int) const
#1  solver: void dealii::FEEvaluationBase<2, 2, float, false, dealii::VectorizedArray<float, 8ul> >::read_write_operation<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> const, dealii::internal::VectorReader<float, dealii::VectorizedArray<float, 8ul> > >(dealii::internal::VectorReader<float, dealii::VectorizedArray<float, 8ul> > const&, std::array<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> const*, 2ul> const&, std::array<std::vector<dealii::ArrayView<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>::value_type const, dealii::MemorySpace::Host>, std::allocator<dealii::ArrayView<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>::value_type const, dealii::MemorySpace::Host> > > const*, 2ul> const&, std::bitset<8ul> const&, bool) const
#2  solver: ExaDG::Structure::NonLinearOperator<2, float>::reinit_cell_derived(dealii::FEEvaluation<2, -1, 0, 2, float, dealii::VectorizedArray<float, 8ul> >&, unsigned int) const
#3  solver: std::_Function_handler<void (dealii::FEEvaluation<2, -1, 0, 2, float, dealii::VectorizedArray<float, 8ul> >&), ExaDG::OperatorBase<2, float, 2>::add_diagonal(dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&) const::{lambda(auto:1&)#1}>::_M_invoke(std::_Any_data const&, dealii::FEEvaluation<2, -1, 0, 2, float, dealii::VectorizedArray<float, 8ul> >&)
#4  solver: dealii::MatrixFreeTools::compute_diagonal<2, -1, 0, 2, float, dealii::VectorizedArray<float, 8ul>, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >(dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> > const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, std::function<void (dealii::FEEvaluation<2, -1, 0, 2, float, dealii::VectorizedArray<float, 8ul> >&)> const&, unsigned int, unsigned int, unsigned int)::{lambda(dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> > const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)#1}::operator()(dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> > const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)
#5  solver: std::_Function_handler<void (dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> > const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&), dealii::MatrixFreeTools::compute_diagonal<2, -1, 0, 2, float, dealii::VectorizedArray<float, 8ul>, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >(dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> > const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, std::function<void (dealii::FEEvaluation<2, -1, 0, 2, float, dealii::VectorizedArray<float, 8ul> >&)> const&, unsigned int, unsigned int, unsigned int)::{lambda(dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> > const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)#1}>::_M_invoke(std::_Any_data const&, dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> > const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)
#6  solver: dealii::internal::MFClassWrapper<dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> >, int, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >::cell_integrator(dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> > const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&) const
#7  solver: dealii::internal::MFWorker<dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> >, int, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>, dealii::internal::MFClassWrapper<dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> >, int, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >, true>::process_range(void (dealii::internal::MFClassWrapper<dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> >, int, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >::* const&)(dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> > const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&) const, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, unsigned int)
#8  solver: dealii::internal::MFWorker<dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> >, int, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>, dealii::internal::MFClassWrapper<dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> >, int, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >, true>::cell(unsigned int)
#9  /homes/wiss/schussri/dealii-candi/dealii/lib/libdeal_II.g.so.9.6.0-pre: dealii::internal::MatrixFreeFunctions::TaskInfo::loop(dealii::internal::MFWorkerInterface&) const
#10  solver: void dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> >::cell_loop<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>, int>(std::function<void (dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> > const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, int const&, std::pair<unsigned int, unsigned int> const&)> const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, int const&, bool) const
#11  solver: void dealii::MatrixFreeTools::compute_diagonal<2, -1, 0, 2, float, dealii::VectorizedArray<float, 8ul>, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >(dealii::MatrixFree<2, float, dealii::VectorizedArray<float, 8ul> > const&, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&, std::function<void (dealii::FEEvaluation<2, -1, 0, 2, float, dealii::VectorizedArray<float, 8ul> >&)> const&, unsigned int, unsigned int, unsigned int)
#12  solver: ExaDG::OperatorBase<2, float, 2>::add_diagonal(dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&) const
#13  solver: ExaDG::OperatorBase<2, float, 2>::calculate_diagonal(dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&) const
#14  solver: ExaDG::OperatorBase<2, float, 2>::calculate_inverse_diagonal(dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&) const
#15  solver: ExaDG::MultigridOperator<2, float, ExaDG::Structure::NonLinearOperator<2, float> >::calculate_inverse_diagonal(dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>&) const
#16  solver: ExaDG::ChebyshevSmoother<ExaDG::MultigridOperatorBase<2, float>, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >::initialize(ExaDG::MultigridOperatorBase<2, float> const&, ExaDG::ChebyshevSmoother<ExaDG::MultigridOperatorBase<2, float>, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >::AdditionalData const&)
#17  solver: ExaDG::ChebyshevSmoother<ExaDG::MultigridOperatorBase<2, float>, dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host> >::update()
#18  solver: std::_Function_handler<void (unsigned int), ExaDG::MultigridPreconditionerBase<2, double>::update_smoothers()::{lambda(unsigned int)#1}>::_M_invoke(std::_Any_data const&, unsigned int&&)
#19  solver: ExaDG::MultigridPreconditionerBase<2, double>::update_smoothers()
#20  solver: ExaDG::Structure::MultigridPreconditioner<2, double>::update()
#21  solver: ExaDG::Krylov::SolverFGMRES<ExaDG::Structure::NonLinearOperator<2, double>, ExaDG::PreconditionerBase<double>, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >::update_preconditioner(bool) const
#22  solver: ExaDG::Newton::Solver<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, ExaDG::Structure::ResidualOperator<2, double>, ExaDG::Structure::LinearizedOperator<2, double>, ExaDG::Krylov::SolverBase<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> > >::solve(dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, ExaDG::Newton::UpdateData const&)
`

### PR DESCRIPTION
**Pull request by richardschu**
after https://github.com/dealii/dealii/pull/15865
we can reintroduce the `&` we removed in #549 
resolves #548

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

File: include/exadg/structure/preconditioners/multigrid_preconditioner.cpp [hunk 1]
```diff
@@ -110,7 +110,7 @@ MultigridPreconditioner<dim, Number>::update()
     // interpolate velocity from fine to coarse level
     this->transfer_from_fine_to_coarse_levels(
       [&](unsigned int const fine_level, unsigned int const coarse_level) {
-        auto vector_fine_level =
+        auto & vector_fine_level =
```
Comment (nfehn) [inline include/exadg/structure/preconditioners/multigrid_preconditioner.cpp:113]: Shouldn't we be able to write `auto const &` here?

Comment (richardschu) [reply include/exadg/structure/preconditioners/multigrid_preconditioner.cpp:113]: yes :)

Comment (richardschu) [reply include/exadg/structure/preconditioners/multigrid_preconditioner.cpp:113]: see #581
